### ISSUE TITLE
#expect does not show output for try expression

### ISSUE THREAD

**Issue by Kyle-Ye** [swiftlang/swift-testing#756] opened 2024-10-09 05:39 UTC
#### Motivation

The original logic is a 3 step computation. 

However I'd like to test multi instance and name the instance with number make me sad. So I compress the steps into one throwing function.

But then the `#expect` macro won't show the output for the left expression with `try`.

```swift
let instance1 = step1(1)
let instance1Data = try step2(instance1)
let instance1String = step3(instance1Data)
#expect(instance1String == "1")

let instance2 = step1(2)
let instance2Data = try step2(instance2)
let instance2String = step3(instance2Data)
#expect(instance2String == "2")

...
```

⬇️

```swift
func helper(_ input: Int) throws -> String {
  let instance = step1(input)
  let data = try step2(instance)
  return step3(data)
}

#expect(try helper(1) == "1")
#expect(try helper(2) == "2")
...
```

#### Reproduce

A simplified version to demonstrate the issue

```swift
enum MultiError: Error {
    case invalidInput
}

func multi(_ a: Int, _ b: Int) throws -> Int {
    guard a > 0, b > 0 else {
        throw MultiError.invalidInput
    }
    return a * b
}

func multiWithoutThrow(_ a: Int, _ b: Int) -> Int {
    return a * b
}

@Test func example() async throws {
    #expect(try multi(1, 2) == 3)
    #expect(multiWithoutThrow(1, 2) == 3)
}
```

### Expected behavior

```
Expectation failed: (try multi(1, 2) → 2) == 3
Expectation failed: (multiWithoutThrow(1, 2) → 2) == 3
```

### Actual behavior

```
Expectation failed: try multi(1, 2) == 3
Expectation failed: (multiWithoutThrow(1, 2) → 2) == 3
```

### Steps to reproduce

See code snippet above 

### swift-testing version/commit hash

Xcode 16.0

**Comment by Kyle-Ye** [comment] 2024-10-09 06:04
A temporary workaround is change it from `#expect(try multi(1, 2) == 3)` to `#expect((try multi(1, 2)) == 3)`

Then we'll get the expected result.
```
Expectation failed: ((try multi(1, 2)) → 2) == 3
```

**Comment by grynspan** [comment] 2024-10-09 11:14
Duplicate of #162

**Closed** 2024-10-09 11:14 UTC
Labels: bug
