### ISSUE TITLE
Fatal error: Internal inconsistency: No test reporter for test case argumentIDs:

### ISSUE THREAD

**Issue by Kyle-Ye** [swiftlang/swift-testing#749] opened 2024-10-07 07:24 UTC
### Description

Related issue: https://github.com/swiftlang/swift/issues/76637#issuecomment-2396120511

Using the trick mentioned above can solve most of my needs.

But it seems I just hit another corner case in swift-tesing.

### Expected behavior

No fatal error.

### Actual behavior

```
XCTest/HarnessEventHandler.swift:282: Fatal error: Internal inconsistency: No test reporter for test case argumentIDs: Optional([Testing.Test.Case.Argument.ID(bytes: [48]), Testing.Test.Case.Argument.ID(bytes: [34, 35, 52, 102, 55, 56, 97, 50, 101, 100, 102, 54, 52, 51, 48, 101, 52, 50, 100, 55, 50, 49, 98, 53, 53, 50, 51, 102, 102, 57, 99, 102, 98, 48, 57, 100, 51, 99, 97, 57, 53, 98, 34])]) in test DemoKitTests.STests/PTypeConformance(value:expected:)/DemoKitTests.swift:5:6
```

### Steps to reproduce

Use provided DemoKit package to reproduce it.

[DemoKit.zip](https://github.com/user-attachments/files/17274804/DemoKit.zip)

### swift-testing version/commit hash

None

### Swift & OS version (output of `swift --version ; uname -a`)

Xcode 16.0.0 with Swift 5 language mode

**Comment by Kyle-Ye** [comment] 2024-10-07 08:16
Close as duplicated of #480

**Comment by Kyle-Ye** [comment] 2024-10-07 08:32
Temporary workaround provided by @Brett-Best

```swift
@Test(.serialized, arguments:
```

**Comment by grynspan** [comment] 2024-10-07 11:11
I believe you're right and this is a duplicate, but @stmontgomery can probably confirm.

**Comment by stmontgomery** [comment] 2024-10-07 22:16
This is _effectively_ a dupe of #480, yes. But this manifestation of the problem is different than what was described in that issue. Here, the problem is that two arguments of a parameterized test have identical ID representations (even though their specific `arguments:` are different.) Either way, I do believe the fixes will be related, so we can dupe this.

Duplicate of #480

**Closed by stmontgomery** 2024-10-07 22:16 UTC
Labels: bug
