### ISSUE TITLE
Add API for writing informational messages in tests

### ISSUE THREAD

**Issue by prachigauriar** [swiftlang/swift-testing#607] opened 2024-08-08 02:49 UTC
### Description

My team uses seeded random value generation throughout our test suites. To ensure that tests are repeatable, we log the seed to the console before each test is run. With XCTest, we did this using `XCTContext.runActivity` as follows:

```swift
open class RandomizedTestCase : XCTestCase, RandomValueGeneratingTestSuite {
    …
    @MainActor
    public var randomSeed: UInt64 {
        …
        set {
            XCTContext.runActivity(named: "Using random seed \(newValue)") { (activity) in
                randomNumberGenerator.seed = newValue
                print(activity.name)
            }
        }
    }

    …

    open override func setUp() async throws {
        try await super.setUp()
        await setRandomSeed(Date.timeIntervalSinceReferenceDate.bitPattern)
    }
}
```

This allows the seed to show up in the console and xcresult bundles. In CI, we extract information from the xcresult bundles to generate HTML test reports, and it’s important that the seeds show up for failed tests so that engineers can repeat the test with the same inputs to diagnose what went wrong.

As best as I can tell, Swift Testing lacks any mechanism to log dynamic informational messages in tests. Console output is not included in the JSON ABI (or xcresult bundles when run from Xcode), so we can’t use `print(…)`. `Issue.record(_:sourceLocation:)` nearly works, but issues are treated like test failures, which is inappropriate for our use case. If there were something like `Message.record(_:sourceLocation:)`, that would probably work well for us.

Without some mechanism for seeing the random seeds in xcresult bundles, we can’t adopt Swift Testing.

If you consider this more an Xcode issue vs. a Swift Testing one, please let me know and I can log something using Feedback Assistant.

### swift-testing version/commit hash

Whichever version is included with Xcode 16 beta 5.

### Swift & OS version (output of `swift --version && uname -a`)

swift-driver version: 1.113 Apple Swift version 6.0 (swiftlang-6.0.0.7.6 clang-1600.0.24.1)
Target: arm64-apple-macosx14.0
Darwin «redacted» 23.6.0 Darwin Kernel Version 23.6.0: Fri Jul  5 17:56:41 PDT 2024; root:xnu-10063.141.1~2/RELEASE_ARM64_T6000 arm64

**Comment by grynspan** [comment] 2024-08-08 09:54
Duplicate of #42

**Closed** 2024-08-08 09:54 UTC
Labels: enhancement

**Comment by NateCost** [comment] 2025-01-24 16:22
Hi, @grynspan 
I have a similar situation. We extract useful information on CI from `runActivity`. I tried to add it to a new Swift Testing test and it doesn't show me activities in the test log. Are there any similar feature planned to be added for Swift Testing?

<img width="1417" alt="Image" src="https://github.com/user-attachments/assets/b25b98da-c926-490c-80bb-4c6099f71d55" />

**Comment by grynspan** [comment] 2025-01-24 21:04
See #42.

**Comment by NateCost** [comment] 2025-01-25 10:18
> See [#42](https://github.com/swiftlang/swift-testing/issues/42).

Yeah, I saw it, it was raised the issue with a runtime error. As you see I don't have any runtime error, but I don't have an activity tab in the test log. So, is there no point of use `XCTContext.runactivity` method inside of a `@Test` test? How can I achieve that activity tab using Swift Testing?

**Comment by grynspan** [comment] 2025-01-25 13:35
The feature doesn't exist in Swift Testing. #42 tracks adding it.
